[env:lilygo-t5-213]
platform = espressif32
framework = arduino
board = esp32dev 
monitor_speed = 115200

lib_deps =
    zinggjm/GxEPD2 @ ^1.5.9
    adafruit/Adafruit GFX Library @ ^1.11.11
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
